
FROM continuumio/miniconda3:4.9.2

MAINTAINER "pericsson"

ENV LC_ALL C.UTF-8
ENV LC_LANG C.UTF-8

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq -y update && apt-get -qq -y upgrade

RUN conda config --add channels bioconda \
	&& conda update --quiet conda \
	&& conda install --yes --quiet \
		krona=2.7.1 \
	&& conda clean --all --yes --quiet

CMD /bin/bash 
