
__default__:
  threads: 1
  queue: cgg_short.q

# Stage 1
unzip_rename_SE:
  threads: 4
  queue: cgg_short.q

unzip_rename_PE:
  threads: 4
  queue: cgg_short.q

quality_control_raw_SE:
  threads: 4
  queue: cgg_short.q

fiona_SE_RNA:
  threads: 40 #110
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

fiona_SE_DNA:
  threads: 40 #110
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

# Stage 2
megahit_SE_RNA:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

megahit_PE_RNA:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

bbwrap_alignment_SE_RNA:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl
  
bbwrap_alignment_PE_RNA_unmerged:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

# Stage 3
kaiju:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl

kraken:
  threads: 40 #120
  queue: cgg_short.q@yavin.medair.lcl #wgs.q@kuat.medair.lcl




#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 120
#$ -q wgs.q@kuat.medair.lcl
#$ -l excl=1