__default__:
  threads: 1
  queue: cgg_short.q

unzip_rename_SE:
  threads: 4
  queue: cgg_short.q

unzip_rename_PE:
  threads: 4
  queue: cgg_short.q

quality_control_raw_SE:
  threads: 4
  queue: cgg_short.q

#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 120
#$ -q wgs.q@kuat.medair.lcl
#$ -l excl=1