# RUN CONFIGURATION

## Input
sampledir: 
  "/apps/bio/dev_repos/parca/demo"
sample: 
- "S04_S5_02_22_41_KV16-8204OM-L_180530.fastq"
- "a.fastq.gz"
- "l.fq"

## Output
#output_folder_date: "" # if empty, a date will be generated in the format yyyy_mm_dd for the output folder
outdir: 
  "/apps/bio/dev_repos/parca/demo"

## Singularity
singularity_image:
  "/apps/bio/dev_repos/parca/parca/workflows/containers/parca_v1.sif"


# Programs
fiona_path: 
  "/apps/bio/software/fiona/0.2.9/bin/fiona"
pollux_path: 
  "/apps/bio/apps/pollux/1.0.2/bin/pollux"