# RUN CONFIGURATION
#illumina:  False #set to true or false or leave empty
RNA: True #set to true or false or leave empty

## Input
sampledir: 
  "/apps/bio/dev_repos/parca/demo/raw_samples"
adapters:
- "None"
samples: #leave empty if you want to use all fastq-files in a sample directory
#- "S04_S5_02_22_41_KV16-8204OM-L_180530"
- "a"
#- "l"
#- SRR1761912

suffix_fwd: ".fastq.gz" #"_1.fastq.gz" #".fastq.gz"
suffix_rev: #"_2.fastq.gz" # Leave empty if single end

## Output
#output_folder_date: "" # if empty, a date will be generated in the format yyyy_mm_dd for the output folder
outdir: 
  "/apps/bio/dev_repos/parca/demo"

## Singularity
singularity_image:
  "/apps/bio/dev_repos/parca/parca/workflows/containers/image_parca_v1.sif"

## Conda environment
conda_environment:
  "/apps/bio/dev_repos/parca/parca/workflows/conda/parca_container_env.yml"


# Programs
pollux_path: 
  "/apps/bio/apps/pollux/1.0.2/bin/pollux"
fiona_path: 
  "/apps/bio/software/fiona/0.2.9/bin/fiona"
