# RUN CONFIGURATION
#illumina:  False #set to true or false or leave empty
RNA: True #set to true or false or leave empty

## Input
sampledir: 
  "/apps/bio/dev_repos/parca/demo/raw_samples"
adapters:
- "None"
samples: #leave empty if you want to use all fastq-files in a sample directory
- "a"
#- "b"
#- "S04_S5_02_22_41_KV16-8204OM-L_180530"
#- "l"
#- SRR1761912

suffix_fwd: ".fastq.gz" #"_1.fastq.gz" #".fastq.gz"
suffix_rev: #"_2.fastq.gz" # Leave empty if single end

## Output
#output_folder_date: "" # if empty, a date will be generated in the format yyyy_mm_dd for the output folder
outdir: 
  "/apps/bio/dev_repos/parca/demo"

## Singularity
singularity_image:
  "/apps/bio/dev_repos/parca/parca/workflows/containers/image_parca_v3.sif"

## Conda environment
conda_environment:
  "/apps/bio/dev_repos/parca/parca/workflows/conda/parca_container_env.yml"

# PROGRAMS
pollux_path: 
  "/apps/bio/apps/pollux/1.0.2/bin/pollux"
fiona_path: 
  "/apps/bio/software/fiona/0.2.9/bin/fiona"
kraken_path: 
  "/apps/CLC_ExternalApps/kraken2"

## Kraken settings
kraken_db_base_path: "/medstore/External_References/krakdb_hll"

krakendb_RNA: ["eukaryotes_cds", "viruses"] #, "bacteria_progenomes_cds_total"]
krakendblimits_RNA: ["0.15", "0.05"] #, "0.05"]

krakendb_DNA: ["eukaryotes_768","viruses","bacteria_progenomes_total_768"]
krakendblimits_DNA: ["0.15","0.05","0.05"]

## Kraken2 settings
kraken2_db_base_path: "/medstore/Development/Metagenomics/kraken_dbs"

kraken2_mini_db: "viruses" #"minikraken_8GB_20200312"
kraken2_limits: "0.05" #["0.15"]

## Kaiju settings
kaiju_db_base_path: "/medstore/Development/Metagenomics/PathFinder43b/databases" #"/tmp/pathfinder_dbs" #cp -r /medstore/Development/Metagenomics/PathFinder43b/databases/* /tmp/pathfinder_dbs
kaiju_names: "/medstore/Development/Metagenomics/PathFinder43b/databases/nodes.dmp" #"/tmp/pathfinder_dbs/nodes.dmp"

kaijudb_RNA: ["genbank_eukaryotes_171014_kaiju_db","genbank_viruses_171017_kaiju_db"] #["progenomes_complete","genbank_eukaryotes_171014_kaiju_db","genbank_viruses_171017_kaiju_db"]
kaijuscore_RNA: ["85","75"] #["80", "85","75"]
kaijumatches_RNA: ["20","15"] #["18","20","15"]
#kaijuerrors_RNA: ["2","2","3"]

kaijudb_DNA: ["progenomes_complete","genbank_eukaryotes_171014_kaiju_db","genbank_viruses_171017_kaiju_db"]
kaijuscore_DNA: ["80", "85","75"]
kaijumatches_DNA: ["18","20","15"]
#kaijuerrors_DNA: ["2","2","3"]

## Nodes and names file
#nodes: "/medstore/Development/Metagenomics/PathFinder43b/databases/nodes.dmp"
#names: "/medstore/Development/Metagenomics/PathFinder43b/databases/names.dmp"
names_nodes_dmp_dir: "/apps/bio/dev_repos/parca/demo/ref/names_and_nodes" #"/medstore/Development/Metagenomics/PathFinder43b/databases"



# BLAST
existing_slice_path: "/medstore/Development/Metagenomics/PathFinder43b/databases/gislices"

splitaccdump_dir: "/medstore/Development/Metagenomics/PathFinder43b/databases/splitaccdump" #accession dump to filter for downloaded accessions

nt_db_dir: "/medstore/Development/Metagenomics/PathFinder43b/databases/nt"