# RUN CONFIGURATION
#run_dict_list: [{'run_id': 'run_1', 'start_date': 20201202, 'case': 'sample_1', 'control': 'sample_2'}, {'run_id': 'run_2', 'start_date': 20201202, 'case': 'sample_2'}]
#metadata_dict: [{'sample_id': 'sample_1', 'nucleotide': 'RNA', 'fwd_or_rev': 'fwd', 'path_to_file': '/apps/bio/dev_repos/parca/demo/raw_samples/SRR1761912_1.fastq.gz', 'adapters': 'NA', 'PE_or_SE': 'PE'}, {'sample_id': 'sample_1', 'nucleotide': 'RNA', 'fwd_or_rev': 'rev', 'path_to_file': '/apps/bio/dev_repos/parca/demo/raw_samples/SRR1761912_2.fastq.gz', 'adapters': 'NA', 'PE_or_SE': 'PE'}, {'sample_id': 'sample_2', 'nucleotide': 'DNA', 'fwd_or_rev': 'fwd', 'path_to_file': '/apps/bio/dev_repos/parca/demo/raw_samples/a.fastq.gz', 'adapters': 'NA', 'PE_or_SE': 'SE'}]

# adapters:
#   - "None"

outdir: 
  "/apps/bio/dev_repos/parca/demo"

singularity_image:
  "workflows/containers/image_parca_v6.sif" #Build complete: /tmp/image-244526401 
  #pyyaml tored in directory: /tmp/pip-ephem-wheel-cache-rz6n2chl/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c

## Set to False if keys from samplePath should be used. If these should be generated, set to True.
generateSampleID: True


## PROGRAMS NOT AVAILABLE IN CONDA
pollux_path: 
  "/apps/bio/apps/pollux/1.0.2/bin/pollux"
fiona_path: 
  "/apps/bio/software/fiona/0.2.9/bin/fiona"

## Kraken
kraken_path: 
  "/apps/CLC_ExternalApps/kraken2" # Seems to be kraken1 even though referred to as kraken2
kraken_db_base_path: "/medstore/External_References/krakdb_hll"

krakendb_RNA: ["viruses", "bacteria_progenomes_cds_total"]  # "eukaryotes_cds"
krakendblimits_RNA: ["0.15", "0.05", "0.05"]

krakendb_DNA: ["viruses", "bacteria_progenomes_total_768"]  # "eukaryotes_768"
krakendblimits_DNA: ["0.15", "0.05", "0.05"]

## Kraken2 settings
kraken2_db_base_path: "/medstore/Development/Metagenomics/kraken_dbs"

kraken2_mini_db: "viruses" #"minikraken_8GB_20200312"
kraken2_limits: "0.05" #["0.15"]

## Kaiju settings
kaiju_db_base_path: "/medstore/Development/Metagenomics/PathFinder43b/databases" #"/tmp/pathfinder_dbs" #cp -r /medstore/Development/Metagenomics/PathFinder43b/databases/* /tmp/pathfinder_dbs 
kaiju_names: "/medstore/Development/Metagenomics/PathFinder43b/databases/nodes.dmp" #"/tmp/pathfinder_dbs/nodes.dmp"

kaijudb_RNA: ["progenomes_complete", "genbank_viruses_171017_kaiju_db"]  # "genbank_eukaryotes_171014_kaiju_db"
kaijuscore_RNA: ["80", "85","75"] #["85","75"]
kaijumatches_RNA: ["18","20","15"] #["20","15"]
#kaijuerrors_RNA: ["2","2","3"]

kaijudb_DNA: ["progenomes_complete", "genbank_viruses_171017_kaiju_db"]  # "genbank_eukaryotes_171014_kaiju_db"
kaijuscore_DNA: ["80", "85","75"]
kaijumatches_DNA: ["18","20","15"]
#kaijuerrors_DNA: ["2","2","3"]

## Nodes and names file
#nodes: "/medstore/Development/Metagenomics/PathFinder43b/databases/nodes.dmp"
#names: "/medstore/Development/Metagenomics/PathFinder43b/databases/names.dmp"
names_nodes_dmp_dir: "/apps/bio/dev_repos/parca/demo/ref/names_and_nodes" #"/medstore/Development/Metagenomics/PathFinder43b/databases"

# # BLAST
existing_slice_path: "/medstore/Development/Metagenomics/PathFinder43b/databases/gislices"

splitaccdump_dir: "/medstore/Development/Metagenomics/PathFinder43b/databases/splitaccdump" #accession dump to filter for downloaded accessions

nt_db_dir: "/medstore/Development/Metagenomics/PathFinder43b/databases/nt"

# Primates file
primates_file: "/medstore/Development/Metagenomics/PathFinder43b/databases/primates_taxids.txt"