# RUN CONFIGURATION

## Set RNA to True for RNA samples and to False for DNA samples
RNA: True

## The keys under samplePath can be set to anything but the length of its value determines whether paired end or single end. The keys needs to have unique names.
samplePath:
  #sample_1: ["/apps/bio/dev_repos/parca/demo/raw_samples/SRR1761912_1.fastq.gz", "/apps/bio/dev_repos/parca/demo/raw_samples/SRR1761912_2.fastq.gz"]
  sample_2: ["/apps/bio/dev_repos/parca/demo/raw_samples/a.fastq.gz"]

## Set to False if keys from samplePath should be used. If these should be generated, set to True.
generateSampleID: True

adapters:
  - "None"

outdir: 
  "/apps/bio/dev_repos/parca/demo/200819_demo"
  #"/apps/bio/dev_repos/parca/demo/200813_demo"

singularity_image:
  "workflows/containers/image_parca_v6.sif" #Build complete: /tmp/image-244526401 
  #pyyaml tored in directory: /tmp/pip-ephem-wheel-cache-rz6n2chl/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c

## PROGRAMS NOT AVAILABLE IN CONDA
pollux_path: 
  "/apps/bio/apps/pollux/1.0.2/bin/pollux"
fiona_path: 
  "/apps/bio/software/fiona/0.2.9/bin/fiona"

## Programs that should be replaced to conda
kraken_path: 
  "/apps/CLC_ExternalApps/kraken2"

## Kaiju settings
kaiju_db_base_path: "/medstore/Development/Metagenomics/PathFinder43b/databases" #"/tmp/pathfinder_dbs" #cp -r /medstore/Development/Metagenomics/PathFinder43b/databases/* /tmp/pathfinder_dbs
kaiju_names: "/medstore/Development/Metagenomics/PathFinder43b/databases/nodes.dmp" #"/tmp/pathfinder_dbs/nodes.dmp"

## Kraken settings
kraken_db_base_path: "/medstore/External_References/krakdb_hll"

## Names and nodes file
names_nodes_dmp_dir: "/apps/bio/dev_repos/parca/demo/ref/names_and_nodes"